"use client";

import { useState } from "react";

interface Goal {
  id: string;
  title: string;
  description: string;
  progress: number;
  category: string;
}

const PLACEHOLDER_GOALS: Goal[] = [
  {
    id: "1",
    title: "Complete weekly task review",
    description: "Review and prioritize all inbox tasks",
    progress: 0,
    category: "Productivity",
  },
  {
    id: "2",
    title: "Delegate more to AI agents",
    description: "Assign at least 3 tasks to AI this week",
    progress: 0,
    category: "Automation",
  },
  {
    id: "3",
    title: "Clear task backlog",
    description: "Reduce inbox to under 5 items",
    progress: 0,
    category: "Organization",
  },
];

export default function Goals() {
  const [goals] = useState<Goal[]>(PLACEHOLDER_GOALS);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateGoals = async () => {
    setIsGenerating(true);
    // TODO: Connect to OpenCode to generate personalized goals
    // This would analyze user's task history, identity.md, user.md
    setTimeout(() => {
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display text-2xl font-light text-[var(--text-primary)]">Goals</h2>
          <p className="text-sm text-[var(--text-secondary)] font-light mt-1">AI-suggested goals based on your activity</p>
        </div>
        <button
          onClick={generateGoals}
          disabled={isGenerating}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-[var(--text-primary)] text-[var(--background)] disabled:opacity-50 transition-opacity"
        >
          <span className="material-icons text-[14px]">auto_awesome</span>
          {isGenerating ? "Generating..." : "Refresh"}
        </button>
      </div>

      {isGenerating ? (
        <div className="flex flex-col items-center py-16">
          <div className="flex gap-1 mb-3">
            <span className="w-2 h-2 bg-[var(--text-secondary)] rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
            <span className="w-2 h-2 bg-[var(--text-secondary)] rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
            <span className="w-2 h-2 bg-[var(--text-secondary)] rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
          </div>
          <p className="text-[var(--text-secondary)] text-sm font-light">Analyzing your task patterns...</p>
        </div>
      ) : (
        <div className="space-y-3">
          {goals.map((goal) => (
            <div
              key={goal.id}
              className="p-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] hover:shadow-sm transition-shadow"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-[var(--background)] text-[var(--text-secondary)] border border-[var(--border)]">
                      {goal.category}
                    </span>
                  </div>
                  <h3 className="text-[15px] text-[var(--text-primary)] font-normal leading-snug">{goal.title}</h3>
                  <p className="text-[12px] text-[var(--text-secondary)] font-light mt-1 leading-relaxed">{goal.description}</p>
                </div>
                <div className="flex-shrink-0 mt-1">
                  <div className="w-10 h-10 rounded-full border-2 border-[var(--border)] flex items-center justify-center">
                    <span className="text-[11px] text-[var(--text-secondary)] font-medium">{goal.progress}%</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      <div className="text-center pt-4">
        <p className="text-[11px] text-[var(--text-secondary)] font-light opacity-60">
          Goals are generated by analyzing your task history and patterns.
          <br />
          Connect OpenCode for personalized suggestions.
        </p>
      </div>
    </div>
  );
}
